"use client";
import React, { useState } from "react";
import { GlassButton, GlassCard, GlassInput, SectionHeader, StatusBadge } from "../ui/glass";

export function DashboardHome({ address, balance, sendOpen, setSendOpen, sendEth }: { address: string; balance: string; sendOpen: boolean; setSendOpen: (open: boolean) => void; sendEth: (recipient: string, amount: string) => Promise<string> }) {
  const [depositOpen, setDepositOpen] = useState(false);
  const [recipient, setRecipient] = useState(""); const [amount, setAmount] = useState("");
  const [asset, setAsset] = useState<"ETH" | "USDC">("ETH"); const [review, setReview] = useState(false);
  const [status, setStatus] = useState(""); const [busy, setBusy] = useState(false);
  async function send() { setBusy(true); setStatus(""); try { const hash = await sendEth(recipient, amount); setStatus(`Confirmed · ${hash.slice(0, 10)}...${hash.slice(-6)}`); setReview(false); } catch (reason) { setStatus(reason instanceof Error ? reason.message : "Transaction failed"); } finally { setBusy(false); } }
  return <div className="module-page wallet-page"><SectionHeader eyebrow="GOOD TO SEE YOU" title="Your wallet" action={<div className="header-wallet"><StatusBadge tone="green">Connected</StatusBadge><button onClick={() => navigator.clipboard.writeText(address)}>{address.slice(0, 8)}...{address.slice(-6)} · Copy</button></div>} />
    <GlassCard className="balance-card"><div><span>Total Balance</span><h2>{Number(balance).toFixed(4)} <small>ETH</small></h2><p>Native asset on Anvil Local</p></div><div className="balance-actions"><GlassButton className="primary-button" onClick={() => setDepositOpen(true)}>↓ <span>Deposit</span></GlassButton><GlassButton onClick={() => setSendOpen(true)}>↑ <span>Send</span></GlassButton></div></GlassCard>
    <div className="dashboard-grid"><section><div className="subhead"><h2>Assets</h2><button>Manage assets</button></div><GlassCard className="asset-list"><Asset symbol="Ξ" name="Ethereum" detail="Native network asset" amount={`${Number(balance).toFixed(4)} ETH`} /><Asset symbol="$" name="USD Coin" detail="ERC-20 stablecoin" amount="0.00 USDC" /></GlassCard></section><section><div className="subhead"><h2>Recent activity</h2><button>View all</button></div><GlassCard className="recent-empty"><span>↗</span><h3>No wallet activity yet</h3><p>Your local transfers and escrow actions will appear here.</p></GlassCard></section></div>
    {depositOpen && <Modal title="Receive assets" close={() => setDepositOpen(false)}><div className="receive-symbol">V</div><p className="modal-copy">Send ETH or supported ERC-20 assets to this address.</p><div className="address-box"><code>{address}</code><button onClick={() => navigator.clipboard.writeText(address)}>Copy</button></div><div className="receive-assets"><StatusBadge>ETH · Native</StatusBadge><StatusBadge>USDC · ERC-20</StatusBadge></div><p className="modal-note">Only send assets available on Anvil Local (chain 31337).</p></Modal>}
    {sendOpen && <Modal title={review ? "Review transaction" : "Send assets"} close={() => { setSendOpen(false); setReview(false); setStatus(""); }}><div className="segmented"><button className={asset === "ETH" ? "selected" : ""} onClick={() => { setAsset("ETH"); setReview(false); }}>ETH</button><button className={asset === "USDC" ? "selected" : ""} onClick={() => { setAsset("USDC"); setReview(false); }}>USDC</button></div>{asset === "USDC" ? <div className="coming-soon"><StatusBadge>Coming soon</StatusBadge><h3>USDC transfers are not configured locally</h3><p>A deployed token address is required before real ERC-20 transfers can be signed.</p></div> : review ? <div className="review-transaction"><span>Sending</span><strong>{amount} ETH</strong><span>To</span><code>{recipient}</code><GlassButton className="primary-button" disabled={busy} onClick={() => void send()}>{busy ? "Broadcasting..." : "Confirm transaction"}</GlassButton></div> : <div className="send-form"><label>Recipient<GlassInput placeholder="0x..." value={recipient} onChange={event => setRecipient(event.currentTarget.value)} /></label><label>Amount<GlassInput type="number" min="0" step="0.001" placeholder="0.00" value={amount} onChange={event => setAmount(event.currentTarget.value)} /></label><GlassButton className="primary-button" disabled={!recipient || !amount} onClick={() => setReview(true)}>Review transaction</GlassButton></div>}{status && <p className="transaction-status">{status}</p>}</Modal>}
  </div>;
}
function Asset({ symbol, name, detail, amount }: { symbol: string; name: string; detail: string; amount: string }) { return <div className="asset-row"><span className="asset-icon">{symbol}</span><div><strong>{name}</strong><small>{detail}</small></div><b>{amount}</b></div>; }
function Modal({ title, close, children }: { title: string; close: () => void; children: React.ReactNode }) { return <div className="modal-backdrop" role="dialog" aria-modal="true"><GlassCard className="glass-modal"><header><h2>{title}</h2><button aria-label="Close" onClick={close}>×</button></header>{children}</GlassCard></div>; }
